### ISSUE TITLE
API - editOrder

### ISSUE THREAD

**Issue by zhongjixiuxing** [chenkaiC4/ccxt#20]
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/8935235/170069707-bb6074e9-84a5-40f9-b444-fa04dec64127.png">

**Comment by zhongjixiuxing** [comment]
现在 call editOrder API , 返回 -1 服务器错误，没有具体的错误提示，不知这类错误是否是调用方错误，还是远程服务器错误导致的？需要 btse 那边支持下

**请求参数**
```
{
  orderID: "d2e08dc3-f057-4f3f-b57e-b716476e3553",
  type: "ALL",
  orderPrice: 7020,
  orderSize: 2,
}
```


**响应结果**
{"code":-1,"msg":null,"time":1653444308285,"data":null,"success":false}

**Comment by yuanchenho** [comment]
@zhongjixiuxing `value` 這個值是為了向前相容
當 type = ALL 的時候就是如你們所帶的
一併帶上 `orderPrice` 跟 `orderSize` 就行
那個 -1 的問題我們研究下後回覆

**Comment by yuanchenho** [comment]
hi @zhongjixiuxing `symbol` 這個參數是必要的
報錯是因為這個

**Comment by chenkaiC4** [comment]
@yuanchenho 谢谢

**Comment by zhongjixiuxing** [comment]
@yuanchenho Hi
返回的数据 symbol 是 “BTC-null”， 这里 null 是不是有问题吖？
price, size 这里应该返回的是修改后的数据，实际 price => 0, size = 1 , 返回数据可以是更新后的订单数据么？


### 请求数据
```
{
  orderID: "d2e08dc3-f057-4f3f-b57e-b716476e3553",
  type: "ALL",
  symbol: "BTC-USD",
  orderPrice: 7020,
  value: 7020,
  orderSize: 2,
}
```

响应数据
```
[
  {
    status: "15",
    symbol: "BTC-null",
    orderType: "0",
    price: "0.0",
    side: "BUY",
    size: "1.0",
    orderID: "d2e08dc3-f057-4f3f-b57e-b716476e3553",
    timestamp: "1653466873692",
    triggerPrice: "0.0",
    stopPrice: null,
    trigger: false,
    message: "",
    averageFillPrice: "0.0",
    fillSize: "0.0",
    clOrderID: "",
    stealth: "0.0",
    deviation: "0.0",
    postOnly: false,
    originalSize: "1.0",
    remainingSize: "1.0",
    time_in_force: "GTC",
  },
]
```
