### ISSUE TITLE
API - Withdraw

### ISSUE THREAD

**Issue by zhongjixiuxing** [chenkaiC4/ccxt#21]
# Withdraw api 可以提供一份完整可用的参数么？在 BTC network 下的。

### 请求参数
```
{
  currency: "BTC",
  amount: "0.0001",
  address: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
  tag: "BTC",
}
```

### 返回参数
```
{"code":10071,"msg":"BADREQUEST: Incorrect transfer parameter","time":1653492496411,"data":null,"success":false}
```

**Comment by yuanchenho** [comment]
@zhongjixiuxing 可以參考一下這一份

https://github.com/btsecom/api-sample/blob/master/nodejs/app/wallet/withdraw-funds.js

主要是 currency 的部分是 `currency-network` pair
細節可以看這邊 https://btsecom.github.io/docs/wallet/en/#withdraw-funds

**Comment by yuanchenho** [comment]
@zhongjixiuxing 有給 `tiancaidev` 打了十個 btc 進去了

**Comment by zhongjixiuxing** [comment]
> @zhongjixiuxing 有給 `tiancaidev` 打了十個 btc 進去了

好的，谢谢

**Comment by zhongjixiuxing** [comment]
> 

@yuanchenho 看下下面这个请求参数, 我得到的结果还是 `{"code":10071,"msg":"BADREQUEST: Incorrect transfer parameter","time":1653583664591,"data":null,"success":false}` 这个我都不知是具体哪个参数有问题了，

### 请求参数
```
{
  currency: "BTC-Bitcoin",
  amount: "0.001",
  address: "1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX",
  tag: "",
}
```

**Comment by yuanchenho** [comment]
@zhongjixiuxing 可以試試用這組參數嗎？
https://github.com/btsecom/api-sample/blob/736fd67fc5a3068e024a806324c49dda8de4de0a/nodejs/app/wallet/withdraw-funds.js#L27

我初步看了一下 有可能是 btc `1 開頭` 的地址是 mainnet 使用的
但我們 testnet 環境對接的是 testnet 所以這個地址檢查過不了
這個我再請同事確認中

**Comment by zhongjixiuxing** [comment]
> @zhongjixiuxing 可以試試用這組參數嗎？ https://github.com/btsecom/api-sample/blob/736fd67fc5a3068e024a806324c49dda8de4de0a/nodejs/app/wallet/withdraw-funds.js#L27
> 
> 我初步看了一下 有可能是 btc `1 開頭` 的地址是 mainnet 使用的 但我們 testnet 環境對接的是 testnet 所以這個地址檢查過不了 這個我再請同事確認中

谢谢回复. 我用 BTC testnet 地址试了，可以正常 withdraw .
