### ISSUE TITLE
API - transfer

### ISSUE THREAD

**Issue by zhongjixiuxing** [chenkaiC4/ccxt#22]
# 需要提供另一个可以接受 transfer 的测试账号来测试，一个账号测试不了

### 请求参数
```
{
  asset: "BTC",
  amount: 0.0001,
  toUser: "toAccount",
  toUserMail: "anxing131@gmail.com",
}
```

### 响应参数
```
{"code":40043,"msg":null,"time":1653493641926,"data":null,"success":false}
```

**Comment by yuanchenho** [comment]
@zhongjixiuxing `40043` 是收款方的 email 不存在
會需要另外一個帳號來收款
你們可以從這個網頁的右上角註冊新帳號嗎？
https://testnet.btse.io/en/home

**Comment by zhongjixiuxing** [comment]
> 
@chenkaiC4  注册地区受限，注册不了新的账号
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/8935235/170410999-33e02225-db90-48e0-b125-774ac53541b2.png">
